### ISSUE TITLE
Running OpenIDM by itself in Kubernetes

### ISSUE THREAD

**Issue by chrissnell** [ForgeRock/fretes#2]
Hi @wstrange,

I am very new to ForgeRock and OpenIDM.  I'm trying to set up a user management system that I can authenticate users against via REST.  OpenIDM seems to fit the bill.  We use Kubernetes heavily here and so, of course, I want to run your software in Kube.   I'm not ready to go full-tilt and set up OpenDJ yet so I just want to keep it simple and use a MySQL table to store my user data.  This MySQL server would live outside of our Kube cluster because we're running a private cloud and don't have persistent volumes yet.

So, here's my first question: can you point me at the set of OpenIDM config files in this repo?   It's not totally clear to me because you're using a gitRepo volume and that seems to mount this entire ```fretes``` repo and that's a lot of stuff.  Where are the actual configs?  

Second question: the Docker image [referenced in your RC](https://github.com/ForgeRock/fretes/blob/master/openidm/openidm.yaml#L30)--will it connect to  a MySQL database out-of-the-box with the  "Database Table Connector"?   I really don't need the entire suite of ForgeRock components that ```fretes``` provides.   I just need a basic OpenIDM installation that will run in Kube and I don't want to start off with OpenDJ before I gain more experience with OpenIDM.
Thanks!

**Comment by wstrange** [comment]
Hi Chris

Probably easiest to reach out to me via email (warren dot strange at forgerock.com )

If you want to authenticate users you will want to use OpenAM.   OpenIDM is a user provisioning system, and is not really meant for authentication.   OpenAM has a REST API for authentication, and also supports standards based AuthN (OpenID connect, for example)

This folder
https://github.com/ForgeRock/fretes/tree/master/openam-pets  

Has a start on an OpenAM deployment. You will need to modify this for your environment. It is harder than it needs to be right now. We are working to make OpenAM 14 easier to deploy on K8S.

Warren
